"""Add integration models

Revision ID: df09a0cd82c5
Revises: 
Create Date: 2025-12-01 21:49:45.584929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df09a0cd82c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    import sqlmodel
    with op.batch_alter_table('sentenceanalysis', schema=None) as batch_op:
        batch_op.alter_column('usage_type',
                   existing_type=sa.VARCHAR(),
                   nullable=False,
                   existing_server_default=sa.text("'analysis'"))

    with op.batch_alter_table('userprofile', schema=None) as batch_op:
        batch_op.alter_column('preferences_json',
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    import sqlmodel
    with op.batch_alter_table('userprofile', schema=None) as batch_op:
        batch_op.alter_column('preferences_json',
                   existing_type=sqlmodel.sql.sqltypes.AutoString(),
                   type_=sa.TEXT(),
                   existing_nullable=True)

    with op.batch_alter_table('sentenceanalysis', schema=None) as batch_op:
        batch_op.alter_column('usage_type',
                   existing_type=sa.VARCHAR(),
                   nullable=True,
                   existing_server_default=sa.text("'analysis'"))
    # ### end Alembic commands ###
